Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"

#  config.vm.define "web" do |web|
#    web.vm.box = "ubuntu/trusty64"
#	web.vm.provision :shell, path: "bootstrap.sh"
#	web.vm.network :forwarded_port, guest: 80, host: 5678
#  end
#  
#  config.vm.define "db" do |db|
#    db.vm.box = "ubuntu/trusty64"
#	db.vm.provision :shell, path: "bootstrap.sh"
#	db.vm.network :forwarded_port, guest: 80, host: 6789
#  end
#
	(1..2).each do |i|
	  config.vm.define "linux#{i}" do |node|
		node.vm.box = "ubuntu/trusty64"
    node.vm.network :private_network, ip: "10.0.15.2#{i}"
    node.vm.provision :shell, path: "bootstrap-linux.sh"
		node.vm.provision "shell",
		  inline: "echo hello from linux #{i}"
	  end
	end  

  # create mgmt node
  config.vm.define :mgmt do |mgmt_config|
      mgmt_config.vm.box = "ubuntu/trusty64"
      mgmt_config.vm.hostname = "mgmt"
      mgmt_config.vm.network :private_network, ip: "10.0.15.10"
      mgmt_config.vm.provider "virtualbox" do |vb|
        vb.memory = "256"
      end
      mgmt_config.vm.provision :shell, path: "bootstrap-ansible.sh"
      mgmt_config.vm.provision :shell, path: "bootstrap-mgmt.sh"
  end

end
