Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"

  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/trusty64"
	web.vm.provision :shell, path: "bootstrap.sh"
	web.vm.network :forwarded_port, guest: 80, host: 5678
  end

  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/trusty64"
	db.vm.provision :shell, path: "bootstrap.sh"
	db.vm.network :forwarded_port, guest: 80, host: 6789
  end

	(1..3).each do |i|
	  config.vm.define "linux#{i}" do |node|
		node.vm.box = "ubuntu/trusty64"
		node.vm.provision "shell",
		  inline: "echo hello from linux #{i}"
	  end
	end  

end
