Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"

  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/trusty64"
	web.vm.provision :shell, path: "bootstrap.sh"
	web.vm.network :forwarded_port, guest: 80, host: 5678
  end

  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/trusty64"
	db.vm.provision :shell, path: "bootstrap.sh"
	db.vm.network :forwarded_port, guest: 80, host: 6789
  end
end
